name: Swift
on:
  push:
  pull_request:

env:
  XCODE_VERSION: "26.0"

jobs:
  build:
    runs-on: "macos-26"
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "generic/platform=iOS"
          - "generic/platform=xrOS"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@v3
      - name: Download MetalToolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Trust plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
      - name: Build (${{ matrix.destination }})
        run: |
          xcodebuild build \
            -project Radiance.xcodeproj \
            -scheme Radiance \
            -destination '${{ matrix.destination }}' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO
